In [ ]:
# Example of List (recap)
# Defining a list (array) in Python
my_list = [1, 2, 3, 4, 5]
print(my_list)

# Accessing elements
print(my_list[0])  # Output: 1

# Modifying elements
my_list[1] = 10
print(my_list)

# Adding elements
my_list.append(6)
print(my_list)

# Removing elements
my_list.remove(3)
print(my_list)


[1, 2, 3, 4, 5]
1
[1, 10, 3, 4, 5]
[1, 10, 3, 4, 5, 6]
[1, 10, 4, 5, 6]


In [ ]:
# Breakdown of the Array Syntax
import array as waklu
import numpy as fsktm
my_array1 = waklu.array('i', [1, 2, 3, 4, 5])
print (my_array1)


my_array2 = fsktm.array([[1, 2, 3, 4],[5,6,7,8]])
print (my_array2)
print (my_array2.ndim)

# Importing the array Module:
# Before using the array module, you need to import it. This is typically done at the top of your Python script:
# Creating the Array:
# The array.array constructor is used to create an array. It takes two main arguments:

# Type Code ('i'):
#The first argument is a type code, which specifies the type of elements the array will hold. In this case, 'i' stands for signed integer. Here are some common type codes:

# 'i': signed integer
# 'f': floating-point
# 'd': double-precision floating-point
# 'b': signed byte
# 'B': unsigned byte
# 'h': signed short integer
# 'H': unsigned short integer
# 'l': signed long integer
# 'L': unsigned long integer

# Initial Values ([1, 2, 3, 4, 5]):
# The second argument is a list of initial values to populate the array. In this example, the array is initialized with the integers 1, 2, 3, 4, and 5



array('i', [1, 2, 3, 4, 5])
[[1 2 3 4]
 [5 6 7 8]]
2


In [1]:
# The array module provides an array data structure that is more space-efficient than lists, but it only supports arrays of basic types.

import array

# Defining an integer array
my_array = array.array('i', [1, 2, 3, 4, 5])
print(my_array)

# Accessing elements
print(my_array[0])  # Output: 1

# Modifying elements
my_array[1] = 10
print(my_array)

# Adding elements
my_array.append(6)
print(my_array)

# Removing elements
my_array.remove(3)
print(my_array)

array('i', [1, 2, 3, 4, 5])
1
array('i', [1, 10, 3, 4, 5])
array('i', [1, 10, 3, 4, 5, 6])
array('i', [1, 10, 4, 5, 6])


In [ ]:
# For numerical computations, the NumPy library provides powerful array objects with many useful functions for mathematical operations.

import numpy as np

# Defining a NumPy array
my_numpy_array = np.array([1, 2, 3, 4, 5])
print(my_numpy_array)

# Accessing elements
print(my_numpy_array[0])  # Output: 1

# Modifying elements
my_numpy_array[1] = 10
print(my_numpy_array)

# Adding elements
my_numpy_array = np.append(my_numpy_array, 6)
print(my_numpy_array)

# Removing elements
my_numpy_array = np.delete(my_numpy_array, 2)  # Removes element at index 2
print(my_numpy_array)

# Summary
# Lists are flexible and can hold elements of different types.
# The array module provides efficient arrays for basic data types.
# NumPy arrays are ideal for numerical and scientific computations.
# Each method has its advantages, and the choice depends on the specific use case and requirements of your program.

[1 2 3 4 5]
1
[ 1 10  3  4  5]
[ 1 10  3  4  5  6]
[ 1 10  4  5  6]


In [2]:
# what is the difference between NumPy arrays and Python arrays?
# NumPy arrays and Python arrays (typically referring to lists or arrays from the array module) are both used to store collections of elements, but they have different features, use cases, and performance characteristics. Here are the key differences:

# 1. Type and Functionality
# Python Lists
# Flexibility: Python lists can store elements of different types (e.g., integers, floats, strings, objects).
# Functionality: Lists support a wide range of operations including append, extend, insert, remove, and many more.
# Dynamic: Lists are dynamically sized, meaning you can add or remove elements easily.

# Python Arrays (array Module)
# Type Restriction: Arrays from the array module are more memory-efficient than lists because they store elements of a single type.
# Limited Functionality: They support fewer operations compared to lists and are intended for numerical data.

# NumPy Arrays
# Type Restriction: NumPy arrays (ndarrays) are homogenous, meaning all elements must be of the same type, which can be more efficient in terms of memory and performance.
# Advanced Functionality: NumPy provides a vast range of mathematical, statistical, and linear algebra operations that are not available with Python lists or the array module.
# Multidimensional: NumPy arrays can be multidimensional (e.g., 2D matrices, 3D tensors), whereas Python lists and array module arrays are typically one-dimensional or require nested lists for multidimensional structures.

# 2. Performance
# Python Lists
# Performance: Lists are slower for numerical computations because they are designed for flexibility rather than speed.
# Overhead: They have a significant overhead due to their dynamic nature and ability to store elements of different types.

# Python Arrays (array Module)
# Performance: Arrays are more efficient than lists for large collections of homogeneous data but still lack the advanced performance optimizations of NumPy.

# NumPy Arrays
# Performance: NumPy arrays are highly optimized for numerical computations and can be significantly faster than lists or arrays from the array module, especially for large datasets.
# Vectorization: NumPy operations are often vectorized, allowing batch operations on data without explicit loops, which greatly enhances performance.

# 3. Memory Usage
# Python Lists
# Memory Usage: Lists have more memory overhead due to their ability to store elements of different types and their dynamic nature.

# Python Arrays (array Module)
# Memory Usage: Arrays use less memory than lists because they store elements of a single type, but still more than NumPy for complex operations.

# NumPy Arrays
# Memory Usage: NumPy arrays are designed to be memory efficient, especially for large numerical datasets. They use contiguous blocks of memory, which enhances performance for numerical operations.

# 4. Ecosystem and Use Cases
# Python Lists
# Ecosystem: Lists are part of the core Python language and are used in a wide range of applications beyond numerical computing.
# Use Cases: General-purpose data structures suitable for most applications where performance is not critical.

# Python Arrays (array Module)
# Ecosystem: Part of the standard library, but not as widely used as lists.
# Use Cases: Suitable for simple numerical data where memory efficiency is important.

# NumPy Arrays
# Ecosystem: NumPy is a foundational library for numerical computing in Python and is widely used in scientific computing, data analysis, machine learning, and engineering.
# Use Cases: Ideal for applications requiring fast numerical computations, linear algebra, Fourier transforms, and operations on large multidimensional arrays.

# Example Comparison:

# List:
my_list = [1, 2, 3, 4, 5]
print(my_list[0])  # Accessing an element
my_list.append(6)  # Adding an element

# Array
import array
my_array = array.array('i', [1, 2, 3, 4, 5])
print(my_array[0])  # Accessing an element
my_array.append(6)  # Adding an element

# NumPy Array
import numpy as np
my_numpy_array = np.array([1, 2, 3, 4, 5])
print(my_numpy_array[0])  # Accessing an element
my_numpy_array = np.append(my_numpy_array, 6)  # Adding an element


1
1
1


In [ ]:
# Codes are from NumPy Chapter
import numpy as np
a1 = np.array(2)
a = np.array([1, 2, 3])
b = np.array([[1, 2],[3, 4]])
c = np.array([[1, 2],[3, 4],[5,6]])
d = np.array([[1, 2, 3 ],[4, 5, 6],[7, 8, 9]])

print(a1)
print(a)
print("array a is a ",a.ndim, " dimension") #check the dimension
print(b)
print("array b is a ",b.ndim, " dimension") #check the dimension

print(c)
print(d)
print("-----------------")
print("Now for 3D array")
e = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],   # First 2D array
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],   # Second 2D array
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]    # Third 2D array
])

print(e)
print("array e is a ",e.ndim, " dimension") #check the dimension

# Accessing an element
print(e[0][1][2])  # Output: 6 (first 2D array, second list, third element)

# Modifying an element
e[1][2][0] = 99
print(e[1][2][0]) # Output: 99 (updated element)
print(e[1][2][1]) # Output: 17

2
[1 2 3]
array a is a  1  dimension
[[1 2]
 [3 4]]
array b is a  2  dimension
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----------------
Now for 3D array
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
array e is a  3  dimension
6
99
17


In [ ]:
# Element-wise Operation
a = np.array([1, 2, 3])
print(a + 2)  # [3, 4, 5]
print(a * 2)  # [2, 4, 6]

# Take note that the elements in a is still the same
print ("-------------------")
print (a)

[3 4 5]
[2 4 6]
-------------------
[1 2 3]


In [ ]:
# Matrix Multiplication
b = np.array([[1, 2], [3, 4]])
c = np.array([[5, 6], [7, 8]])
print(np.dot(b, c))


[[19 22]
 [43 50]]


In [ ]:
# NumPy Indexing Access

a = np.array([1, 2, 3])
print(a[0])  # 1


In [ ]:
# NumPy Slicing
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b[:, 1])  # [2, 5]

print(b[:,0])   # [1, 4]

print(b[0:,])   # [4, 5, 6]

[2 5]
[1 4]
[[1 2 3]
 [4 5 6]]


In [3]:
# Example of NumPy Functions
# np.zeros(), np.ones(), np.full(), np.eye()
a = np.array([1, 2, 3, 4])
print(a.sum())  # 10
print(a.mean())  # 2.5

# Try to find the way the above methods are used (other than sum() and mean() methods)


10
2.5


In [ ]:
# Example of NumPy Functions
#	Generate random numbers:

a = np.random.rand(3, 100)  # Uniformly distributed between 0 and 1
b = np.random.randint(0, 10, (3, 3))  # Random integers between 0 and 10

print(a)
print(b)

[[0.50302352 0.9151385  0.63841538 0.30942004 0.88355943 0.17165199
  0.32890114 0.73154872 0.81818814 0.07219252 0.14702562 0.70516545
  0.82644364 0.85877158 0.95213995 0.76200337 0.40986662 0.8983301
  0.73866248 0.1812544  0.77390551 0.13853043 0.17405627 0.50887565
  0.87621762 0.01366355 0.61913044 0.02453806 0.51613126 0.72298405
  0.9333893  0.42626997 0.28420979 0.48465556 0.20440483 0.93491513
  0.16100146 0.2175063  0.41605512 0.9733555  0.90057615 0.65521463
  0.01626004 0.89981516 0.45503148 0.81082834 0.73063055 0.70972958
  0.58726119 0.5904435  0.85834131 0.60201268 0.71976937 0.99391991
  0.91371379 0.82830975 0.26137719 0.56422631 0.28558953 0.2645644
  0.53363166 0.76104713 0.85939513 0.46073259 0.62580013 0.33534296
  0.68834428 0.57145647 0.92189083 0.85940351 0.18094401 0.20973619
  0.82127435 0.04260104 0.15697589 0.72400474 0.45436065 0.97272275
  0.03082391 0.12395028 0.45623119 0.08422512 0.16901423 0.59465492
  0.35202056 0.23101496 0.14859963 0.80793512 0.15

In [ ]:
# Broadcasting in NumPy Arrays

a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print(a)
print(b)
print(a + b)


[1 2 3]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [4]:
https://colab.research.google.com/drive/15o6u6I1xOGD8sNYnn6M1L4kWV1ZWU9cg?authuser=1#scrollTo=oPGYYUK6zs8c&line=1&uniqifier=1

SyntaxError: invalid decimal literal (<ipython-input-4-ecabfa57a29c>, line 1)

In [ ]:
np.random.seed(21)
random_integers = np.random.randint(1,high=500000, size=(20, 5))
print (random_integers)

[[ 80842 333008 202553 140037  81969]
 [ 63857  42105 261540 481981 176739]
 [489984 326386 110795 394863  25024]
 [ 38317  49982 408830 485118  16119]
 [407675 231729 265455 109413 103399]
 [174677 343356 301717 224120 401101]
 [140473 254634 112262  25063 108262]
 [375059 406983 208947 115641 296685]
 [444899 129585 171318 313094 425041]
 [188411 335140 141681  59641 211420]
 [287650   8973 477425 382803 465168]
 [  3975  32213 160603 275485 388234]
 [246225  56174 244097   9350 496966]
 [225516 273338  73335 283013 212813]
 [ 38175 282399 318413 337639 379802]
 [198049 101115 419547 260219 325793]
 [148593 425024 348570 117968 107007]
 [ 52547 180346 178760 305186 262153]
 [ 11835 449971 494184 472031 353049]
 [476442  35455 191553 384154  29917]]
